export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const LOGGED_OUT = 'LOGGED_OUT';
export const CITY_STATE = 'CITY_STATE';
export const FORM_STATE = 'FORM_STATE';


export const REQUEST_WEATHER = 'REQUEST_WEATHER';
export const RECEIVE_WEATHER = 'RECEIVE_WEATHER';
export const REJECT_WEATHER = 'REJECT_WEATHER';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const RESPOND_LOGIN = 'RESPOND_LOGIN';
export const REJECT_LOGIN = 'REJECT_LOGIN';

export const REQUEST_SIGNUP = 'REQUEST_SIGNUP';
export const RESPOND_SIGNUP = 'RESPOND_SIGNUP';
export const REJECT_SIGNUP = 'REJECT_SIGNUP';

export const REQUEST_USERDATA = 'REQUEST_USERDATA';
export const RESPOND_USERDATA = 'RESPOND_USERDATA';
export const REJECT_USERDATA = 'REJECT_USERDATA';

export const WHEATHER_TIME = 'WHEATHER_TIME';
